# Generated by Django 2.1.7 on 2019-03-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_num', models.PositiveSmallIntegerField()),
                ('field_num', models.PositiveSmallIntegerField()),
                ('data_flt', models.DecimalField(decimal_places=10, max_digits=19)),
                ('data_str', models.CharField(max_length=20)),
                ('uploaded_by', models.CharField(max_length=30)),
                ('data_pt_num', models.PositiveIntegerField()),
                ('data_pt_type', models.CharField(choices=[('flt', 'Float'), ('str', 'string')], default='flt', max_length=3)),
            ],
        ),
    ]
