# Generated by Django 2.1.7 on 2019-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_num', models.PositiveSmallIntegerField()),
                ('field_num', models.PositiveSmallIntegerField()),
                ('data', models.DecimalField(decimal_places=10, max_digits=19)),
                ('uploaded_by', models.CharField(max_length=30)),
                ('data_pt_num', models.PositiveIntegerField()),
                ('upload_success', models.BooleanField(default=True)),
            ],
        ),
    ]
