# Generated by Django 2.2 on 2019-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IotData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("channel_num", models.PositiveSmallIntegerField()),
                ("field_num", models.PositiveSmallIntegerField()),
                ("data", models.DecimalField(decimal_places=10, max_digits=19)),
                ("user", models.CharField(max_length=50)),
            ],
        )
    ]
