# Generated by Django 2.2 on 2019-04-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_data', '0002_remove_iotdata_data_pt_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdata',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
