# Generated by Django 2.2 on 2019-04-18 03:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20190417_2028'),
        ('iot_data', '0003_auto_20190411_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdata',
            name='channel',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='iotdata', to='channels.Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iotdata', to='channels.User'),
        ),
    ]
