# Generated by Django 2.1.7 on 2019-03-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_num', models.PositiveSmallIntegerField()),
                ('created_by', models.CharField(max_length=30)),
                ('fields', models.CharField(max_length=30)),
            ],
        ),
    ]
