# Generated by Django 2.2 on 2019-04-18 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_num', models.PositiveSmallIntegerField()),
                ('fields', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
        migrations.AddField(
            model_name='channel',
            name='allowed_users',
            field=models.ManyToManyField(related_name='channels', to='channels.User'),
        ),
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channels.User'),
        ),
    ]
